services:
  app:
    # build: .
    image: lizlovelace/bountybyte:latest
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=main_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:16
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres-data:
    name: ${POSTGRES_VOLUME_NAME} 
